### ISSUE TITLE
[Bug] Event indicator not showing

### ISSUE THREAD

**Issue by Goirich** [lilcodelab/Xamarin.Plugin.Calendar#11]
I have the problem that the event indicator is not showing on some special days. 
To reproduce start the calendar in june add some events for june and one for new DateTime(2019, 5, 27). The 27. May will be shown but when i switch the month to may the event indicator is gone... 

![june](https://user-images.githubusercontent.com/51700597/59261378-a0ca0a80-8c3d-11e9-8a16-889f445ebf4e.png)
![mai](https://user-images.githubusercontent.com/51700597/59261379-a0ca0a80-8c3d-11e9-80f9-91c6b130989d.png)

**Comment by PenguinPero** [comment]
I will take a look into it tonight :)

**Comment by PenguinPero** [comment]
For me it is working fine

![photo_2019-06-11_20-20-48](https://user-images.githubusercontent.com/28543914/59296681-da733380-8c86-11e9-9a6d-029ee85d39b0.jpg)
![photo_2019-06-11_20-20-48 (2)](https://user-images.githubusercontent.com/28543914/59296682-db0bca00-8c86-11e9-81e8-3174d0fd61b2.jpg)

This is the code in my VM:
![image](https://user-images.githubusercontent.com/28543914/59296705-e8c14f80-8c86-11e9-805a-8f866ede8f04.png)


Could you maybe give me more details
Did you use something other than Add or indexer to insert items to EventCollection?
Which CultureInfo are you using?
Or maybe simple reproduction project?

**Comment by PenguinPero** [comment]
I see that it is an iOS screenshot?
Did you take the screenshot on simulator or device?

Cause simulators can often be buggy and not refresh the UI

**Comment by Goirich** [comment]
I read the events only for one month. When the month is changed new events will be read from the server and added with Events.Add to the collection. 

But i have solved my problem by now. It was a dumb mistake with the height of the calendar. I'am very sorry for that. After fixing that problem i also had a problem refreshing the ui. Now i add the events with a delay and it works fine. 

await Task.Delay(100).ContinueWith(_ =>
{
   context.Events.Add(rowDay.dtDate, new List<EventModel>());
}, TaskScheduler.FromCurrentSynchronizationContext());

Thank you for your help and sorry for taking your time.

**Comment by PenguinPero** [comment]
hmm Events.Add should refresh the calendar, I mean call the LoadDays on MonthDaysView
I see that you closed the issue, but is this calendar's fault?
Should you be doing workarounds or should I fix it somehow?
