### ISSUE TITLE
[Custom] Can I Binding Command In EventTemplate?

### ISSUE THREAD

**Issue by tkezyo** [lilcodelab/Xamarin.Plugin.Calendar#12]
I want click event and navigate to other page,but it's not working. help me pls 

    <controls:Calendar.EventTemplate>
                    <DataTemplate>
                        <Button Command="{Binding OpenDetailPageCommand}" Text="{Binding .} "/>
                    </DataTemplate>
    </controls:Calendar.EventTemplate>

**Comment by tkezyo** [comment]
<controls:Calendar.EventTemplate>
                    <DataTemplate>
                        <Button Command="{Binding BindingContext.OpenDetailPageCommand, Source={x:Reference page} }" Text="{Binding .} "/>
                    </DataTemplate>
                </controls:Calendar.EventTemplate>

**Comment by alfredinete** [comment]
i have a external control where i binding my comand
but it still doesn't work

whether in my control with static layout recognizers or buttom

does it bind all commands except the command....

How can I get this way to work?

<DataTemplate x:Name="DtCalendar" >
                                 
                                <StackLayout HorizontalOptions="StartAndExpand">
                                    <Hnb:HnbItemCalendar
                                        x:Name="ItemTasksToday"
                                        x:Uid="ItemTasksToday"
                                        TextTitleColorCtrl="#666666"
                                        TextInfoColorCtrl="#666666"
                                        TextInfoCtrl="{Binding   Description}"
                                        TextTitleCtrl= "{Binding Title}"
                                        BackgroundColorCtrl="#FFFFFF"
                                        CornerRadiusCtrl="5"
                                        BorderColorCtrl="#CCCCCC"
                                        TextRightCtrl="{Binding Hour}"
                                        IsStateColor="True"
                                        StateBckColor="{Binding ColorPriority }"
                                        BtnSelectCommand="{Binding **ComandDetailtask**,Mode=TwoWay}"
                                        BtnSelectCommandParameter="{Binding .}"
                                        IsEnabled="True"
                                       >
                                    </Hnb:HnbItemCalendar>
                                  
                                </StackLayout>

 </DataTemplate>

why does it only work with an external button inside the datatemplate?
 <DataTemplate>
<Button Command="{Binding BindingContext.ComandDetailtask, Source={x:Reference this} }" CommandParameter="{Binding .} "/>
 </DataTemplate>
