### ISSUE TITLE
How to install this plugin(xamarin.plugin.calendar) in PCL xamarin forms.[Bug] Bug title

### ISSUE THREAD

**Issue by Venkatesh-Sudhi** [lilcodelab/Xamarin.Plugin.Calendar#16]
**Describe the bug**
How to install this plugin(xamarin.plugin.calendar) in PCL xa,arin forms.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version information:**
 - Plugin version: ?
 - Xamarin.Forms version: ?
 - Platform: ?

**Additional context**

**Comment by PenguinPero** [comment]
you should be able to install NuGet via Solution > Manage nuget packages, or something else the issue?

**Comment by PenguinPero** [comment]
Since I didn't get any response I will assume you made it work :)
