### ISSUE TITLE
Hide Label Under Calendar (DefaultFooterSection)

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [lilcodelab/Xamarin.Plugin.Calendar#17]
-- need to hide label under calendar which display current today and year
![Screenshot_1568538268](https://user-images.githubusercontent.com/30314037/64919256-9d986a80-d7a8-11e9-82b4-d11e20c6432c.png)

**Comment by PenguinPero** [comment]
@jsabic exposing new property, something like DefaultFooterVisible should be enough

**Comment by PenguinPero** [comment]
implemented in: https://github.com/lilcodelab/Xamarin.Plugin.Calendar/pull/26
closing
