### ISSUE TITLE
Arrows not working on android 9.1

### ISSUE THREAD

**Issue by ksu11** [lilcodelab/Xamarin.Plugin.Calendar#19]
**Describe the bug**
I usea a basic implementation of the pluing, works perfect on IOS but in Android the arrows aren't showing properly

![Screenshot (30 oct 2019 10_17_18)](https://user-images.githubusercontent.com/31185902/67877135-03e20e00-fb07-11e9-8e14-b2df1ced1a33.png)

**Comment by PenguinPero** [comment]
this might depend on your device font settings, I am not actually sure
maybe we can replace arrows with some universal symbol

@jsabic

**Comment by PenguinPero** [comment]
@antonioseric this will be fixed with font icons?

**Comment by antonioseric** [comment]
for now work around is to create custom header and footer. soon it will be in sample app (#36 )
