### ISSUE TITLE
Event indicator shows issue

### ISSUE THREAD

**Issue by StefanVam** [lilcodelab/Xamarin.Plugin.Calendar#22]
I have saw closed issue #8 ,but when i used calender plugin,i still encounter this problem.Is There something wrong when i use.Below is my code
```
protected async override void OnAppearing()
        {
                ...
                var data = (await GetMonthDayData(userId,DateTime.Now)).Data;
                data.ForEach(x => {
                    if((x.customerList!=null)&&(x.customerList.Count>0))
                    {
                        calendar.Events.Add(x.Date, x.customerList);
                    }
               ...
        }
```
  In iOS,when i lanch app through cold start,event indicator which assigned in async onappearing method seems not to show on the initial time.After initialization,event indicator will show if I swipe left or right.
  In Android,this problem just occur occasionally.

**Comment by StefanVam** [comment]
When I move  code to contructor function,Event indicator seems to display correctly on the initial time.

**Comment by StefanVam** [comment]
I think the issue is caused by async

**Comment by PenguinPero** [comment]
@jsabic  will take a look into it

**Comment by jsabic** [comment]
I could not reproduce the issue.

I've tried the following things:
- Add duplicate dates to Events collection
- Not setting events collection
- Not running operation on UI thread

Every case crashes the app. Make sure you did not do any of the above.
