### ISSUE TITLE
Add Solar Calendar View (PerisanCalendar)

### ISSUE THREAD

**Issue by AliDeV7** [lilcodelab/Xamarin.Plugin.Calendar#27]
Hello, Your CalendarView is so Great,but it doesn't work for Solar Calendar (PersianData). CultorInfo("fa-IR") Just Change the name of days.

Please Add this Thnaks

**Comment by PenguinPero** [comment]
We did not plan to add this, it would be a completely different control and would need to be selected with some view-switching mechanism
If you want you can implement it and raise a PR, but we are not familiar with it and it would take too much time to implement
