### ISSUE TITLE
[Bug] Calendar hiding when loaded

### ISSUE THREAD

**Issue by maniakalen** [lilcodelab/Xamarin.Plugin.Calendar#33]
**Describe the bug**
The Calendar disappears once the page is loaded.

**To Reproduce**
1. Initialize the calendar

**Screenshots**
![imagen](https://user-images.githubusercontent.com/4747524/75860352-f9f55200-5dfb-11ea-9b29-e002a54a4844.png)

**Version information:**
    PackageReference Include="Xamarin.Forms" Version="4.5.0.356"
    PackageReference Include="Xamarin.Essentials" Version="1.5.0"
    PackageReference Include="Xamarin.Plugin.Calendar" Version="1.1.925"

**Comment by chbjh** [comment]
I am seeing the same issue. The calendar events flash up very briefly during initial load, but then they disappear just like in the screenshot @maniakalen provided.

**Comment by tdamir** [comment]
Same problem here. If you set MinimumDate and MaximumDate properties, then calendar is showing.

**Comment by chbjh** [comment]
I can confirm that just setting the DayTappedCommand property seems to fix this issue, as @tdamir stated.

**Comment by maniakalen** [comment]
If this is not a bug at least this requirement should be mentioned in the documentation, right?

**Comment by chbjh** [comment]
@maniakalen I can't see how this isn't a bug. This is definitely a bug. 

I can also confirm this did not happen in an older version (1.0.3.200).

**Comment by antonioseric** [comment]
we will fix bug in next few days. Thank you for reporting.

**Comment by antonioseric** [comment]
It will be fixed in next version.
