### ISSUE TITLE
It would be better if Xamarin.Plugin.Calendar can support weekview

### ISSUE THREAD

**Issue by tal-athena** [lilcodelab/Xamarin.Plugin.Calendar#37]
I have seen there is a branch for the week-view. I would like to ask if it's merged to master.
if yes, how can I use it?
if no, could you merge it to master, so we can use week-view?

**Comment by antonioseric** [comment]
@tal-athena this is duplicated issue. please comment on #23 
At this moment week-view is not stabile it contains some bugs that are needed to be fixed before merge to master.
