### ISSUE TITLE
[Custom] Event Background Fill colors based on condition. dot colors is okay but background color need to fill

### ISSUE THREAD

**Issue by harshalgr8** [lilcodelab/Xamarin.Plugin.Calendar#40]
Hi,

i liked the control and it full filing all the need most of we use.

i am looking for a way to show event fill color.

example.
attendence days are events for me. and if present then that event day should be green and if absent then red.

i am looking for a way to fill event background color  based on condition.

please guide me how to achive it.

Thanking You,
Harshal

**Comment by antonioseric** [comment]
@harshalgr8 you can acheave that by crating custom [Event control](https://github.com/lilcodelab/Xamarin.Plugin.Calendar/blob/master/src/Calendar.Plugin.Sample/SampleApp/Controls/CalenderEvent.xaml) than you can add Background and bind it to your ViewModel

**Comment by harshalgr8** [comment]
> @harshalgr8 you can acheave that by crating custom [Event control](https://github.com/lilcodelab/Xamarin.Plugin.Calendar/blob/master/src/Calendar.Plugin.Sample/SampleApp/Controls/CalenderEvent.xaml) than you can add Background and bind it to your ViewModel

![WhatsApp Image 2020-04-29 at 7 32 29 PM](https://user-images.githubusercontent.com/6663858/80605988-603fcf00-8a51-11ea-84ec-fc79724899ea.jpeg)

hi i have used DayEventCollection to achive , dot color based on condition. but i am am not able to achieve background circle on event days.  bigger circle look more better than small dot.

can you add one sample in your existing project, showing hot to achieve circle on events .

Thanking You,
Harshal
