### ISSUE TITLE
[Feature Request] Show the month scroller at the bottom of the calendar

### ISSUE THREAD

**Issue by cristiproj** [lilcodelab/Xamarin.Plugin.Calendar#42]
**Is your feature request related to a problem? Please describe.**
I have a requirement to have the month scroller at the bottom of the page.

**Describe the solution you'd like**
Have the ability to have the month scroller at the top or bottom.

**Describe alternatives you've considered**
Alternative 1. I thought about calling a public method from my own content view to scroll the months.
Alternative 2. Adding another  <controls:DataTemplateView ... /> at the bottom of the Calendar.xaml, identical to the top one. Add two flags, each for one template, so I can show whichever one I want displayed.

**Additional context**
I chose the second alternative. I created a fork of your library and added the changes mentioned.
The git url is: https://github.com/cristiproj/Xamarin.Plugin.Calendar/tree/flags_for_top_bottom_headersectiontemplate

**Comment by antonioseric** [comment]
@cristiproj You can add your header in footer. 
You can check out here sample: https://github.com/lilcodelab/Xamarin.Plugin.Calendar/tree/sample-botom-calendar-navigation

**Comment by cristiproj** [comment]
@antonioseric Thank you for the suggestion with the footer!
