### ISSUE TITLE
[Feature Request] Month selector under the EventTemplate

### ISSUE THREAD

**Issue by cristiproj** [lilcodelab/Xamarin.Plugin.Calendar#46]
**Is your feature request related to a problem? Please describe.**
The requirement I have is to have the footer selector under the EventTemplate. 

**Describe the solution you'd like**
I would like to have another template, as a bottom template, under the EventTemplate.

**Describe alternatives you've considered**
I do not have any alternatives.

**Additional context**
I will make the changes and submit a pull request in a couple of days.

**Comment by antonioseric** [comment]
this is not needed since you can put in footer already anything. You can customize footer to look like this:
![image](https://user-images.githubusercontent.com/4761328/111515990-b7c35800-8753-11eb-83be-b6d9d0eb9e38.png)
