### ISSUE TITLE
[Feature Request] Use Calendar to select date periods not only days

### ISSUE THREAD

**Issue by danilkurkin1** [lilcodelab/Xamarin.Plugin.Calendar#51]
**Is your feature request related to a problem? Please describe.**
Use calendar to select date periods. Where you can use selector on what mode you would like to use: days, weeks, month

**Describe the solution you'd like**
Have Panel with Radio buttons to switch between selection mode Day/Week/Month
Select a date is present
Select week - on tapping the date selecting all dates in the row and return Selected Period (start / finish date maybe?)
Select month - Present grid with months to select from.

**Describe alternatives you've considered**

**Additional context**

**Comment by antonioseric** [comment]
Closed by #80
