### ISSUE TITLE
[Bug] Android select Day

### ISSUE THREAD

**Issue by OsvaldirJr** [lilcodelab/Xamarin.Plugin.Calendar#53]
**Describe the bug**

When you select a day that has no events and select a day that has events and after that you try to select a day with events, the list is blank.
Android only

**To Reproduce**
1. Select a Day with no events
2. select a day with events
3. select another day with events

**Expected behavior**
Show events when have events

**Screenshots**

https://drive.google.com/file/d/1LxKsp6TbFvBHUDX0naKEITdfehI9tRLB/view

**Version information:**
 - Plugin version: 1.2.1506
 - Xamarin.Forms version: 4.7.1179
 - Platform: Android

**Comment by antonioseric** [comment]
@OsvaldirJr can you open screenshots for public or upload them elsewhere. Thank you

Did you try to replicate that behavior on sample app?
