### ISSUE TITLE
Change Today Text Color

### ISSUE THREAD

**Issue by housecode** [lilcodelab/Xamarin.Plugin.Calendar#59]
Please add support to change today text color and today selected/deselected text color

**Comment by antonioseric** [comment]
Please check advanced sample [here](https://github.com/lilcodelab/Xamarin.Plugin.Calendar/blob/6d9482389e0ebfe784933d2a233221026bffcaaa/src/Calendar.Plugin.Sample/SampleApp/Views/AdvancedPage.xaml#L50)

**Comment by bbazina** [comment]
Closed by #79
