### ISSUE TITLE
[Feature Request] Stacklayout Vertical

### ISSUE THREAD

**Issue by usascheduler** [lilcodelab/Xamarin.Plugin.Calendar#63]
**Is your feature request related to a problem? Please describe.**
The Stacklayout vertically is not code into the stack layout.
When When set app.xaml Global propery is   <Style TargetType="StackLayout"  Property="Orientation" Value="Horizontal"/>

Then the calendar header aligns incorrect to default global horizontally 
Month|Days|Events (incorrect)

And needs to be below each other
Moths
Days
Events

**Describe the solution you'd like**
At each vertical stackLayout please add   <StackLayout>   Orientation="Vertical" >

**Describe alternatives you've considered**
At each vertical stackLayout please add   <StackLayout>   Orientation="Vertical" >

**Additional context**
![screenshot](https://user-images.githubusercontent.com/35217301/97891572-8ee67d00-1cf4-11eb-99c3-541922e626ac.jpg)

**Comment by antonioseric** [comment]
#78 Closes this issue
