### ISSUE TITLE
[Feature Request] Custom color for arrow circle

### ISSUE THREAD

**Issue by Naamloos** [lilcodelab/Xamarin.Plugin.Calendar#65]
**Is your feature request related to a problem? Please describe.**
I am unable to set the arrow circle color. Looking at the code this seems to be hardcoded to the color `White`.

**Describe the solution you'd like**
I'd like an additional property to set this color.

**Describe alternatives you've considered**
I considered making my own fork but for such a small change it is not worth the effort.

**Additional context**
![](https://i.imgur.com/JZHMdUo.png)

**Comment by antonioseric** [comment]
You can customize it and make your header template. Check advanced sample [custom header](https://github.com/lilcodelab/Xamarin.Plugin.Calendar/blob/master/src/Calendar.Plugin.Sample/SampleApp/Controls/CalendarHeader.xaml)
