### ISSUE TITLE
[Bug] Swipe to change month not working in Master Detail Page

### ISSUE THREAD

**Issue by housecode** [lilcodelab/Xamarin.Plugin.Calendar#69]
Just embed `AdvancedPage` sample to `Detail` of `MasterDetailPage` and try to swipe the calendar,
and you will see the swipe won't work.

**Steps To Reproduce**
1. Checkout sample project
2. Create new `MasterDetailPage` class and set `AdvancedPage` as the `Detail`
3. Run and then swipe the calendar
4. See the swipe won't work

**Expected behavior**
Should working as expected

**Version information:**
 - Plugin version: 1.2.2936
 - Xamarin.Forms version: 4.8.0.1687
 - Platform: iOS
 - Idiom: Phone

**Additional info**
Only seen this issue in iPhone/iPhone Simulator

**Comment by giuseppenovielli** [comment]
@housecode you can use swipe, but must disable MasterDetail IsGestureEnabled=false

use MessagingCenter to set True or False

<MasterDetailPage
    IsGestureEnabled="{Binding IsGestureEnabled}"

**Comment by housecode** [comment]
Hi @giuseppenovielli is it possible to use `IsGestureEnabled=True` along with Swipe to change month?

**Comment by giuseppenovielli** [comment]
> Hi @giuseppenovielli is it possible to use `IsGestureEnabled=True` along with Swipe to change month?
> I don't want to reduce `MasterDetailPage` behavior

i think this is available only on Android

**Comment by antonioseric** [comment]
This is not bug in plugin. you must handle it in your code.
