### ISSUE TITLE
Setting CultureInfo to "de-DE"

### ISSUE THREAD

**Issue by MxPie200** [lilcodelab/Xamarin.Plugin.Calendar#84]
How can i set the CultureInfo?
What I want to do is to set the calendar's "language" to German so the Day names are in German and the First Day Of Week is Monday.
But I can't find anything how to achieve it.

The only result I got is a System.ArgumentOutOfRangeException: 
![grafik](https://user-images.githubusercontent.com/81758431/115255729-d63fb900-a12e-11eb-97ed-2921791288b7.png)

**Comment by antonioseric** [comment]
this is fixed in #76
