### ISSUE TITLE
[Custom] SelectionType option

### ISSUE THREAD

**Issue by Lukas182** [lilcodelab/Xamarin.Plugin.Calendar#91]
Hello! 

Awesome plugin on here! thanks for your work!

Im using the last downloadable version 1.2.2936 on my PCL project and the same version on iOS/Android platforms.

When I try to use the parameter :

SelectionType="Range"

It's not being found , is cos is not yet available on this on version or I am doing something wrong? 

Thanks for your time!

Regards,

David.

**Comment by subbotted** [comment]
I am also looking for a solution to this

**Comment by mrlacey** [comment]
Based on [this PR](https://github.com/lilcodelab/Xamarin.Plugin.Calendar/pull/93) it looks like the work to fully support this is still in progress.

**Comment by m-luketin** [comment]
@mrlacey you are correct, the feature should be out soon when performance issues are resolved

**Comment by antonioseric** [comment]
Resolved in #93 and #96
