### ISSUE TITLE
Change Localization language

### ISSUE THREAD

**Issue by JanDa-ma** [lilcodelab/Xamarin.Plugin.Calendar#97]
Hi there,

In the description is given that we can change the Localization with System.Globalization.CultureInfo but I can't see how.

Can you give me the information to change the localization(Automatic or via code change)?

**Comment by bbazina** [comment]
You can change it with this property.
https://github.com/lilcodelab/Xamarin.Plugin.Calendar/blob/7da7d1d81527032b5a0251bd8d5e5770817697fe/src/Calendar.Plugin.Sample/SampleApp/Views/AdvancedPage.xaml#L25

**Comment by bbazina** [comment]
You can change it in code behind like this:
`calendar.Culture = new CultureInfo("hr-HR");`
and in xaml you add: 
 `x:Name="calendar"`
